// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Gatsby from "gatsby";

var Link = {};

var pageStyles = {
  color: "#232129",
  fontFamily: "-apple-system, Roboto, sans-serif, serif",
  padding: "96px"
};

var headingStyles = {
  marginTop: "0",
  marginBottom: "64",
  maxWidth: "320"
};

var paragraphStyles = {
  marginBottom: "48"
};

var codeStyles = {
  backgroundColor: "#FFF4DB",
  color: "#8A6534",
  fontSize: "1.25rem",
  padding: "4",
  borderRadius: "4"
};

function NotFound(Props) {
  var match = process.env.NODE_ENV;
  return React.createElement("main", {
              style: pageStyles
            }, React.createElement("title", undefined, "Not found"), React.createElement("h1", {
                  style: headingStyles
                }, "Page not found"), React.createElement("p", {
                  style: paragraphStyles
                }, "Sorry ", React.createElement("span", {
                      "aria-label": "Pensive emoji",
                      role: "img"
                    }, "😔"), " we couldn\xe2\x80\x99t find what you were looking for. ", React.createElement("br", undefined), match === "development" ? React.createElement(React.Fragment, undefined, React.createElement("br", undefined), "Try creating a page in ", React.createElement("code", {
                            style: codeStyles
                          }, "src/pages/"), React.createElement("br", undefined)) : React.createElement(React.Fragment, undefined), React.createElement("br", undefined), React.createElement(Gatsby.Link, {
                      to: "/",
                      children: "Go home"
                    }), "."));
}

var make = NotFound;

export {
  Link ,
  pageStyles ,
  headingStyles ,
  paragraphStyles ,
  codeStyles ,
  make ,
  
}
/* react Not a pure module */
